$(eval $(call PackageDir,qca-nss-fw-cp-enterprise,qca-nss-fw-cp-enterprise,))
$(eval $(call PackageDir,qca-nss-fw-cp-retail,qca-nss-fw-cp-retail,))
$(eval $(call PackageDir,qca-nss-fw-hk-enterprise,qca-nss-fw-hk-enterprise,))
$(eval $(call PackageDir,qca-nss-fw-hk-retail,qca-nss-fw-hk-retail,))
$(eval $(call PackageDir,qca-nss-fw-mp-enterprise,qca-nss-fw-mp-enterprise,))
$(eval $(call PackageDir,qca-nss-fw-mp-retail,qca-nss-fw-mp-retail,))
$(eval $(call PackageDir,qca-nss-fw2-enterprise,qca-nss-fw2-enterprise,))
$(eval $(call PackageDir,qca-nss-fw2-retail,qca-nss-fw2-retail,))
